package tv.twitch.android.models.settings;


public enum  SettingsDestination { // TODO: __REPLACE_CLASS
    // TWITCH STUFF --->
    Account,
    ChangePassword,
    ChannelNotifications,
    ClearAmazonLogin,
    CommunityGuidelines,
    CreateRoom,
    Credits,
    Dashboard,
    DeleteAccount,
    EditProfile,
    EditRoom,
    EditBio,
    EmailNotifications,
    EmailSettings,
    EmailSettingsUnverified,
    EntityInformation,
    InAppNotifications,
    Legal,
    Licenses,
    Notifications,
    PersonalizedAds,
    PersonalizedAdVendorGoogle,
    PersonalizedAdVendorBranchio,
    PersonalizedAdVendorComScore,
    PersonalizedAdVendorNielsen,
    PersonalizedAdVendorSalesforce,
    PhoneNumberSettings,
    Preferences,
    Presence,
    PushNotifications,
    RecommendationsFeedback,
    RecommendationsFeedbackPerCategory,
    RecommendationsFeedbackPerChannel,
    RecommendationsFeedbackPerVideos,
    Rooms,
    SecurityPrivacy,
    Settings,
    Subscriptions,
    System,
    TwoFactorAuthenticationEnable,
    TwoFactorAuthenticationDisable,
    ViewerChatFilters,
    // <--- TWITCH STUFF

    BttvEmotes,
    Chat,
    Player,
    Swiper,
    View,
    Patches
}
